DROP TABLE USERS CASCADE CONSTRAINT;
DROP TABLE COMMENTS CASCADE CONSTRAINT;
DROP TABLE REPLY CASCADE CONSTRAINT;

CREATE TABLE USERS (
	USER_ID 	VARCHAR2(32) NOT NULL PRIMARY KEY,
	USER_NAME 	VARCHAR2(50) NOT NULL,
	PHONE 		VARCHAR2(20),
	ADDRESS 	VARCHAR2(50)
);

CREATE TABLE COMMENTS (
	COMMENT_NO	NUMBER NOT NULL PRIMARY KEY,
	USER_ID 	VARCHAR2(32) NOT NULL REFERENCES USERS(USER_ID),
	COMMENT_CONTENT VARCHAR2(256) NOT NULL,
	REG_DATE 	DATE NOT NULL
);

CREATE TABLE REPLY (
	REPLY_ID 	NUMBER NOT NULL PRIMARY KEY,
	COMMENT_NO	NUMBER NOT NULL	REFERENCES COMMENTS(COMMENT_NO),
	USER_ID		VARCHAR2(32) NOT NULL REFERENCES USERS(USER_ID),
	REPLY_CONTENT	VARCHAR2(256) NOT NULL,
	REG_DATE 	DATE NOT NULL
);

INSERT INTO USERS VALUES ('user1', 'Scott', '010-9967-2406', '서울시 강남구 삼성동 10-2');
INSERT INTO USERS VALUES ('user2', 'Tiger', '010-5891-3399', '서울시 마포구 합정동 50-1');
INSERT INTO USERS VALUES ('user3', 'Admin', '010-3842-2234', '서울시 성북구 월곡동 20-3');

COMMIT;